import { useEffect, useMemo, useState, type ReactNode } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Navbar } from "@/components/layout/Navbar";
import { Helmet } from "react-helmet-async";
import { toast } from "sonner";
import { ArrowRight, BriefcaseBusiness, CheckCircle2, CreditCard, FileSignature, LayoutDashboard, Loader2, Plus, ReceiptText, PanelsTopLeft, WalletCards, X } from "lucide-react";

type Tab = "overview" | "services" | "agreements" | "billing";
type Invoice = { id?: string; amount?: string; due_date?: string; status?: string; description?: string };
type Meta = { agreement?: string; agreements?: { name?: string; status?: string; url?: string }[]; invoices?: Invoice[]; deadline?: string };
type Project = { id: string; name: string; email: string; organization: string | null; designation: string | null; inquiry_type: string; message: string; status: string | null; progress: number | null; bounty_reward: string | null };

const services = [
  ["Business automation", "Remove repetitive work with secure AI and workflow systems.", "2–6 weeks"],
  ["Website & commerce", "A fast, conversion-led website built for your business.", "3–8 weeks"],
  ["SaaS platform", "A scalable product experience from discovery through launch.", "6–16 weeks"],
  ["ERP solution", "Connected operations, reporting and controls for growing teams.", "8–20 weeks"],
] as const;
const meta = (value: string | null): Meta => { try { return value?.trim().startsWith("{") ? JSON.parse(value) : value ? { agreement: value } : {}; } catch { return {}; } };

export default function ClientPortal() {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true), [email, setEmail] = useState(""), [name, setName] = useState(""), [projects, setProjects] = useState<Project[]>([]), [tab, setTab] = useState<Tab>("overview"), [setup, setSetup] = useState(false), [payment, setPayment] = useState<{ project: Project; invoice: Invoice } | null>(null), [mode, setMode] = useState("UPI / Google Pay"), [reference, setReference] = useState(""), [saving, setSaving] = useState(false), [setupSaving, setSetupSaving] = useState(false), [profileComplete, setProfileComplete] = useState(false);
  const load = async (clientEmail: string) => { const { data, error } = await supabase.from("contact_submissions").select("*").eq("email", clientEmail.toLowerCase()).order("created_at", { ascending: false }); if (error) throw error; setProjects((data || []) as Project[]); };
  useEffect(() => { supabase.auth.getSession().then(async ({ data: { session } }) => { if (!session?.user.email) return navigate("/auth"); if (!session.user.user_metadata?.role) return navigate("/portal"); setEmail(session.user.email); setName(session.user.user_metadata?.full_name || session.user.email.split("@")[0]); setProfileComplete(Boolean(session.user.user_metadata?.organization?.trim() && session.user.user_metadata?.designation?.trim())); try { await load(session.user.email); } catch { toast.error("Your workspace could not be loaded."); } finally { setLoading(false); } }); }, [navigate]);
  const invoices = useMemo(() => projects.flatMap(project => (meta(project.bounty_reward).invoices || []).map(invoice => ({ project, invoice }))), [projects]);
  const outstanding = invoices.filter(({ invoice }) => !["paid", "settled"].includes((invoice.status || "").toLowerCase()));
  const sendPayment = async () => { if (!payment || !reference.trim()) return toast.error("Enter your UTR or bank reference."); setSaving(true); const note = `\n[PAYMENT SUBMITTED: ${payment.invoice.id || "Invoice"} | ${mode} | Ref: ${reference.trim()} | ${new Date().toISOString()}]`; const { error } = await supabase.from("contact_submissions").update({ message: payment.project.message + note }).eq("id", payment.project.id); setSaving(false); if (error) return toast.error(error.message); toast.success("Payment submitted for verification."); setPayment(null); setReference(""); };
  const completeSetup = async (organization: string, designation: string) => { setSetupSaving(true); const { error } = await supabase.auth.updateUser({ data: { organization, designation } }); setSetupSaving(false); if (error) return toast.error(error.message); setProfileComplete(true); toast.success("Profile saved. You can now start your service request."); setSetup(false); navigate(`/submit?type=requirement&organization=${encodeURIComponent(organization)}`); };
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#f7f5ef]"><Loader2 className="h-7 w-7 animate-spin text-primary" /></div>;
  const hasSetup = profileComplete || projects.some((project) => Boolean(project.organization?.trim() && project.designation?.trim()));
  const tabs: [Tab, string, typeof LayoutDashboard][] = [["overview", "Overview", LayoutDashboard], ["services", "Services", PanelsTopLeft], ["agreements", "Agreements", FileSignature], ["billing", "Billing", WalletCards]];
  return <div className="min-h-screen bg-[#f7f5ef] text-[#29251d]"><Helmet><title>Client Workspace | Siddhi Dynamics</title></Helmet><Navbar /><main className="mx-auto max-w-6xl px-4 pb-16 pt-28 sm:px-6">
    <section className="rounded-[28px] bg-[#292a22] px-6 py-8 text-white shadow-xl shadow-stone-900/10 sm:px-9"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-lime-300">Siddhi Dynamics · Client workspace</p><h1 className="mt-2 text-3xl font-semibold sm:text-4xl">Good to see you, {name.split(" ")[0]}.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-stone-300">Your projects, decisions, documents and bills—without the clutter.</p></div><button onClick={() => navigate("/submit?type=requirement")} className="inline-flex items-center justify-center gap-2 rounded-xl bg-lime-300 px-4 py-3 text-sm font-bold text-stone-950"><Plus className="h-4 w-4" /> Start a request</button></div></section>
    <nav className="mt-6 flex gap-1 overflow-x-auto rounded-2xl border border-stone-200 bg-white p-1.5">{tabs.map(([id, label, Icon]) => <button key={id} onClick={() => setTab(id)} className={`flex shrink-0 items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold ${tab === id ? "bg-stone-900 text-white" : "text-stone-500 hover:bg-stone-100"}`}><Icon className="h-4 w-4" />{label}</button>)}</nav>
    {tab === "overview" && <div className="mt-7 space-y-6">{!hasSetup && <div className="flex flex-col gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">Finish your client profile</p><p className="mt-1 text-sm text-stone-600">Add your organisation and billing contact before an agreement or invoice is issued.</p></div><button onClick={() => setSetup(true)} className="rounded-lg bg-stone-900 px-4 py-2 text-sm font-bold text-white">Complete setup</button></div>}<div className="grid gap-4 sm:grid-cols-3">{[["Active projects", projects.length, "In your workspace", BriefcaseBusiness], ["Action needed", outstanding.length, "Open bills", CreditCard], ["Delivery progress", projects.length ? `${Math.round(projects.reduce((sum, p) => sum + (p.progress || 0), 0) / projects.length)}%` : "—", "Average across projects", CheckCircle2]].map(([label, value, hint, Icon]: any) => <div key={label} className="rounded-2xl border border-stone-200 bg-white p-5"><Icon className="h-5 w-5 text-primary" /><p className="mt-6 text-2xl font-semibold">{value}</p><p className="mt-1 text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-stone-500">{hint}</p></div>)}</div><Panel title="Your work" subtitle="A focused view of active engagements.">{projects.length ? <div className="divide-y divide-stone-100">{projects.map(project => <div key={project.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{project.organization || project.inquiry_type || "New project"}</p><p className="mt-1 max-w-xl truncate text-sm text-stone-500">{project.message || "Requirements are being reviewed."}</p><span className="mt-3 inline-block rounded-full bg-stone-100 px-2.5 py-1 text-xs font-bold text-stone-600">{project.status || "Discovery"}</span></div><Progress value={project.progress || 0} /></div>)}</div> : <Empty icon={BriefcaseBusiness} title="No active work yet" description="Choose a service and send your goals. We’ll return with a clear scope and proposal." action="Explore services" onClick={() => setTab("services")} />}</Panel></div>}
    {tab === "services" && <section className="mt-7"><Heading eyebrow="Choose an outcome" title="Services designed around your next move." body="Start a focused request. We confirm scope, timeline and price before any work begins." /><div className="grid gap-4 md:grid-cols-2">{services.map(([title, body, timing]) => <article key={title} className="rounded-2xl border border-stone-200 bg-white p-6"><span className="rounded-full bg-lime-50 px-3 py-1 text-xs font-bold text-primary">{timing}</span><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-stone-600">{body}</p><button onClick={() => navigate(`/submit?type=requirement&service=${encodeURIComponent(title)}`)} className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-primary">Request this service <ArrowRight className="h-4 w-4" /></button></article>)}</div></section>}
    {tab === "agreements" && <section className="mt-7"><Heading eyebrow="Approvals" title="Agreements, without the uncertainty." body="Review a scope, request a change, and keep the signed version in one place." /><div className="space-y-3">{projects.flatMap(project => { const m = meta(project.bounty_reward); const agreements = m.agreements?.length ? m.agreements : m.agreement ? [{ name: m.agreement, status: "Ready for review" }] : []; return agreements.map((agreement, i) => <div key={`${project.id}-${i}`} className="flex flex-col gap-4 rounded-2xl border border-stone-200 bg-white p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-violet-50 text-violet-700"><FileSignature className="h-5 w-5" /></div><div><p className="font-semibold">{agreement.name || "Service agreement"}</p><p className="mt-1 text-sm text-stone-500">{project.organization || project.inquiry_type}</p></div></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">{agreement.status || "Ready for review"}</span></div>); })}</div>{!projects.some(p => meta(p.bounty_reward).agreement || meta(p.bounty_reward).agreements?.length) && <Panel><Empty icon={FileSignature} title="No agreement ready" description="Once your scope is confirmed, your agreement will arrive here for review and signature." /></Panel>}</section>}
    {tab === "billing" && <section className="mt-7"><Heading eyebrow="Billing" title="Simple, traceable payments." body="Pay by UPI or bank transfer and submit a reference for finance to verify." /><div className="space-y-3">{invoices.map(({ project, invoice }, i) => { const paid = ["paid", "settled"].includes((invoice.status || "").toLowerCase()); return <div key={`${project.id}-${i}`} className="flex flex-col gap-4 rounded-2xl border border-stone-200 bg-white p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><ReceiptText className="h-5 w-5" /></div><div><p className="font-semibold">{invoice.id || "Project invoice"} · {invoice.amount || "Amount pending"}</p><p className="mt-1 text-sm text-stone-500">{invoice.description || project.organization || "Siddhi Dynamics service"}{invoice.due_date ? ` · Due ${invoice.due_date}` : ""}</p></div></div><div className="flex items-center gap-3"><span className={`rounded-full px-3 py-1 text-xs font-bold ${paid ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{invoice.status || "Pending"}</span>{!paid && <button onClick={() => setPayment({ project, invoice })} className="rounded-lg bg-stone-900 px-3.5 py-2 text-sm font-bold text-white">Pay now</button>}</div></div>; })}</div>{!invoices.length && <Panel><Empty icon={CreditCard} title="No bills issued" description="When a quote is approved, your invoice and payment schedule will appear here." /></Panel>}</section>}
  </main>{setup && <Setup name={name} email={email} onClose={() => setSetup(false)} onComplete={completeSetup} saving={setupSaving} />}{payment && <Payment invoice={payment.invoice} mode={mode} setMode={setMode} reference={reference} setReference={setReference} onClose={() => setPayment(null)} onSubmit={sendPayment} saving={saving} />}</div>;
}
function Heading({ eyebrow, title, body }: { eyebrow: string; title: string; body: string }) { return <div className="mb-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">{eyebrow}</p><h2 className="mt-2 text-2xl font-semibold">{title}</h2><p className="mt-2 text-sm text-stone-600">{body}</p></div>; }
function Panel({ title, subtitle, children }: { title?: string; subtitle?: string; children: ReactNode }) { return <section className="overflow-hidden rounded-2xl border border-stone-200 bg-white">{title && <div className="border-b border-stone-100 px-5 py-4"><h2 className="font-semibold">{title}</h2><p className="mt-0.5 text-sm text-stone-500">{subtitle}</p></div>}{children}</section>; }
function Progress({ value }: { value: number }) { return <div className="w-full sm:w-40"><div className="flex justify-between text-xs font-bold"><span>Progress</span><span>{value}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-stone-100"><div className="h-full rounded-full bg-primary" style={{ width: `${value}%` }} /></div></div>; }
function Empty({ icon: Icon, title, description, action, onClick }: { icon: any; title: string; description: string; action?: string; onClick?: () => void }) { return <div className="px-6 py-14 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-stone-100 text-stone-500"><Icon className="h-5 w-5" /></div><h3 className="mt-4 font-semibold">{title}</h3><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-stone-500">{description}</p>{action && <button onClick={onClick} className="mt-5 text-sm font-bold text-primary">{action}</button>}</div>; }
function Setup({ name, email, onClose, onComplete, saving }: { name: string; email: string; onClose: () => void; onComplete: (organization: string, designation: string) => void; saving: boolean }) { const [organization, setOrganization] = useState(""), [designation, setDesignation] = useState(""); return <div className="fixed inset-0 z-50 grid place-items-center bg-stone-950/45 p-4"><form onSubmit={e => { e.preventDefault(); onComplete(organization, designation); }} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">One-time setup</p><h2 className="mt-1 text-xl font-semibold">Complete your client profile</h2></div><button type="button" onClick={onClose}><X className="h-5 w-5" /></button></div><p className="mt-3 text-sm text-stone-600">Start with the details we use for your scope, agreement and billing.</p><div className="mt-5 grid gap-4"><label className="text-sm font-bold">Organisation<input required value={organization} onChange={e => setOrganization(e.target.value)} placeholder="Company or business name" className="mt-2 w-full rounded-xl border border-stone-200 px-3 py-3 font-normal outline-none focus:border-primary" /></label><label className="text-sm font-bold">Your role<input required value={designation} onChange={e => setDesignation(e.target.value)} placeholder="e.g. Founder, Operations Manager" className="mt-2 w-full rounded-xl border border-stone-200 px-3 py-3 font-normal outline-none focus:border-primary" /></label></div><p className="mt-5 text-xs text-stone-500">{name} · {email}</p><button disabled={saving} className="mt-5 w-full rounded-xl bg-stone-900 py-3 text-sm font-bold text-white disabled:opacity-60">{saving ? "Saving…" : "Save & start service request"}</button></form></div>; }
function Payment({ invoice, mode, setMode, reference, setReference, onClose, onSubmit, saving }: { invoice: Invoice; mode: string; setMode: (v: string) => void; reference: string; setReference: (v: string) => void; onClose: () => void; onSubmit: () => void; saving: boolean }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-stone-950/45 p-4"><div className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">Payment submission</p><h2 className="mt-1 text-xl font-semibold">{invoice.id || "Invoice"} · {invoice.amount || ""}</h2></div><button onClick={onClose}><X className="h-5 w-5" /></button></div><div className="mt-6 grid grid-cols-2 gap-2">{["UPI / Google Pay", "Bank transfer"].map(item => <button key={item} onClick={() => setMode(item)} className={`rounded-xl border p-3 text-left text-sm font-bold ${mode === item ? "border-primary bg-primary/5 text-primary" : "border-stone-200"}`}>{item}</button>)}</div><p className="mt-5 rounded-xl bg-stone-50 p-4 text-sm text-stone-600">Use the payment details on your invoice. Finance verifies every payment before this bill is marked paid.</p><label className="mt-5 block text-sm font-bold">UTR / payment reference<input value={reference} onChange={e => setReference(e.target.value)} placeholder="e.g. 427891003210" className="mt-2 w-full rounded-xl border border-stone-200 px-3 py-3 font-normal outline-none focus:border-primary" /></label><button disabled={saving} onClick={onSubmit} className="mt-5 flex w-full justify-center rounded-xl bg-stone-900 py-3 text-sm font-bold text-white disabled:opacity-60">{saving ? "Submitting…" : "Submit for verification"}</button></div></div>; }
