server.port=9090

# Supabase Credentials (from .env)
supabase.url=https://xoqpxckowwubeqdtazks.supabase.co
supabase.publishable.key=sb_publishable_Db5k1uOh50NIY-GPvMm0HQ_OMnOz8D7
# Gateway Proxy for ISP Bypass
supabase.proxy.ip=172.64.149.246

# Logging
logging.level.com.siddhidynamics=DEBUG
