// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// In dev mode, route through the Vite proxy to bypass ISP-level DNS/TLS interception.
// The Vite server proxies /supabase-api → supabase.co at the Node.js level.
const EFFECTIVE_URL = import.meta.env.DEV
    ? "/supabase-api" // Relative path works better with Vite proxy
    : SUPABASE_URL;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.error("Missing Supabase credentials in .env file");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(EFFECTIVE_URL, SUPABASE_ANON_KEY);